### ISSUE TITLE
Please provide jdk11 version in repo

### ISSUE THREAD

**Issue by xbloom** [rohansuri/adaptive-radix-tree#3]
JDK11 is the LTS version. Could you please upload artifact in that version?

**Comment by rohansuri** [comment]
Just created [1.0.1-beta](https://bintray.com/rohansuri/adaptive-radix-tree/adaptive-radix-tree/1.0.1-beta) built with Java 8. Give it a try.

**Comment by xbloom** [comment]
It looks good, Thank U
