### ISSUE TITLE
[QUESTION] Java class version of the Jcenter release

### ISSUE THREAD

**Issue by TonioGela** [rohansuri/adaptive-radix-tree#4]
Hello @rohansuri, this is more a question than a issue.
I tried using you ART implementation for a personal project, but I soon realized that the only release available is compiled using Java 12 as per this message:
`Caused by: java.lang.UnsupportedClassVersionError: com/github/rohansuri/art/BinaryComparable has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

I'm curious, is there a specific reason for this? Like maybe, GC reasons, etc...
Thanks btw, awesome work.

**Comment by rohansuri** [comment]
Hi @TonioGela, the latest [1.0.1-beta](https://bintray.com/rohansuri/adaptive-radix-tree/adaptive-radix-tree/1.0.1-beta) is built with Java 8, give it a try.

There's no specific reason really. Java 12 was the latest release when I started work on this.

**Comment by TonioGela** [comment]
Okay, thanks for the info!
